pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "project.views"
    

  config:
    DEBUG: true
    TESTING: false
    APP_NAME: pyms_celery
    APPLICATION_ROOT : /pyms_celery
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    DATABASE: db.sqlite3
    SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3
    CELERY_BROKER_URL: redis://host:port/0
    CELERY_RESULT_BACKEND: redis://host:port/0 
    